Added work of native back button
IraSoro/peri pull request #58
Opened 2023-06-16 13:43 UTC by IraSoro

2023-06-16 15:02 UTC, imblowfish requested changes

2023-06-18 19:11 UTC, IraSoro commented on src/App.tsx
> +const PeriApp: React.FC = () => {
Fixed

2023-06-18 19:11 UTC, IraSoro commented on src/App.tsx
> +export default PeriApp;
Fixed too

2023-06-18 19:11 UTC, IraSoro commented on src/modals/CalendarModal.tsx
> +                            onClick={() => props.setIsOpen(false)}
Fixed

2023-06-18 19:13 UTC, IraSoro commented on src/pages/TabHome.tsx
> +            <InfoModal isOpen={isInfoModal} setIsOpen={setIsInfoModal} />
Ok

2023-06-18 19:15 UTC, IraSoro commented on src/modals/InfoModal.tsx
> +            <IonButton
Ok. I'll make a formatting task.

2023-06-18 19:20 UTC, IraSoro commented on src/pages/TabHome.tsx
> +      if (isCalendarModal) {
Code fixed, good idea. But the transition to the "/home" is needed, without it it does not work. This is a feature of the native back button.

2023-06-18 22:05 UTC, IraSoro commented on src/pages/TabHome.tsx
> +import { useHistory } from 'react-router';
Fixed

2023-06-18 22:05 UTC, IraSoro commented on src/pages/TabHome.tsx
> +        history.push('/home');
Changed to `useIonRouter`

2023-06-18 22:50 UTC, imblowfish approved these changes

2023-06-18 23:31 UTC, imblowfish commented
I fixed merge conflicts, @IraSoro could you please verify that all ok now?

2023-06-19 10:06 UTC, merged